create table if not exists public.t_test
(
    id          bigint    default nextval('t_test_id_seq'::regclass) not null
    primary key,
    name        varchar(255)                                         not null,
    age         integer,
    salary      double precision,
    created_at  timestamp default CURRENT_TIMESTAMP,
    updated_at  timestamp default CURRENT_TIMESTAMP,
    deleted_at  timestamp,
    email       varchar(255)
    unique,
    password    varchar(255),
    active      boolean   default true,
    description varchar(255),
    address     jsonb,
    tags        text[],
    is_deleted  boolean                                              not null
    );

alter table public.t_test
    owner to mind_card;

-- 思维卡片表
create table if not exists public.cards
(
    id            bigint generated by default as identity primary key,
    title         varchar(200) not null,                    -- 卡片标题
    content       text,                                     -- 卡片内容
    category      varchar(100),                             -- 分类
    tags          varchar(500),                             -- 标签，逗号分隔
    priority      integer      default 0,                   -- 优先级 0-低 1-中 2-高
    status        varchar(20)  default 'ACTIVE',            -- 状态：ACTIVE, ARCHIVED, DELETED
    color         varchar(20)  default '#FFFFFF',           -- 卡片颜色
    is_favorite   boolean      default false,               -- 是否收藏
    is_public     boolean      default false,               -- 是否公开
    view_count    integer      default 0,                   -- 查看次数
    created_by    varchar(100),                             -- 创建者
    updated_by    varchar(100),                             -- 更新者
    created_at    timestamp(6) not null default CURRENT_TIMESTAMP,
    updated_at    timestamp(6) default CURRENT_TIMESTAMP,
    deleted_at    timestamp(6),                             -- 软删除时间
    
    -- 索引
    constraint cards_status_check check (status in ('ACTIVE', 'ARCHIVED', 'DELETED')),
    constraint cards_priority_check check (priority >= 0 and priority <= 2)
);

-- 创建索引
create index if not exists idx_cards_status on public.cards(status);
create index if not exists idx_cards_category on public.cards(category);
create index if not exists idx_cards_priority on public.cards(priority);
create index if not exists idx_cards_created_at on public.cards(created_at);
create index if not exists idx_cards_created_by on public.cards(created_by);
create index if not exists idx_cards_is_favorite on public.cards(is_favorite);
create index if not exists idx_cards_is_public on public.cards(is_public);

alter table public.cards
    owner to mind_card;

create table if not exists public.users
(
    id         bigint generated by default as identity
    primary key,
    created_at timestamp(6) not null,
    is_deleted boolean      not null,
    updated_at timestamp(6),
    avatar_url varchar(255),
    email      varchar(100) not null
    constraint uk6dotkott2kjsp8vw4d0m25fb7
    unique,
    is_active  boolean,
    nickname   varchar(50),
    password   varchar(255) not null,
    role       varchar(255) not null
    constraint users_role_check
    check ((role)::text = ANY ((ARRAY ['ADMIN'::character varying, 'USER'::character varying])::text[])),
    username   varchar(50)  not null
    constraint ukr43af9ap4edm43mmtq01oddj6
    unique
    );

alter table public.users
    owner to mind_card;

